#include <stdio.h>
#include <conio.h>
int main(){
    char c;
    do{
         int i;
         int exa1[10];
         int exa2[10];
         int exa3[10];
         int exa4[10];
         int exa5[10];
         int exa6[10];
         int exa7[10];
         int exa8[10];
         int exa9[10];
         int exa10[10];
         int exa11[10];
         int exa12[10];
         int exa13[10];
         int exa14[10];
         int exa15[10];
         int exa16[10];
         int exa17[10];
         int exa18[10];
         int exa19[10];
         int exa20[10];
         int exa21[10];
         int exa22[10];
         float average=0.0;
         float average1=0.0;
         float average2=0.0;
         float average3=0.0;
         float average4=0.0;
         float average5=0.0;
         char name[10][20];
         char surname[10][20];
         for(i=0;i<2;i++){
                           printf("Please enter your name : ");
                           scanf("%s",name[i]);
                           fflush(stdin);
                           printf("Please enter your surname : ");
                           scanf("%s",surname[i]);
                           fflush(stdin);
                           
         printf("Calculus : \n");
                           printf("Please enter 1st quiz mark : ");
                           scanf("%d",&exa1[i]);
                           fflush(stdin);
                           printf("Please enter 2nd quiz mark: ");
                           scanf("%d",&exa2[i]);
                           fflush(stdin);
                           printf("Please enter mid-term mark : ");
                           scanf("%d",&exa3[i]);
                           fflush(stdin);
                           printf("Please enter final mark : ");
                           scanf("%d",&exa4[i]);
                           fflush(stdin);
                            
         printf("Computer Programming - I : \n");
                           printf("Please enter 1st quiz mark : ");
                           scanf("%d",&exa5[i]);
                           fflush(stdin);
                           printf("Please enter 2nd quiz mark: ");
                           scanf("%d",&exa6[i]);
                           fflush(stdin);
                           printf("Please enter mid-term mark : ");
                           scanf("%d",&exa7[i]);
                           fflush(stdin);
                           printf("Please enter final mark : ");
                           scanf("%d",&exa8[i]);
                           fflush(stdin);
                           
          printf("Physics - I : \n");
                           printf("Please enter 1st quiz mark : ");
                           scanf("%d",&exa9[i]);
                           fflush(stdin);
                           printf("Please enter 2nd quiz mark: ");
                           scanf("%d",&exa10[i]);
                           fflush(stdin);
                           printf("Please enter mid-term mark : ");
                           scanf("%d",&exa11[i]);
                           fflush(stdin);
                           printf("Please enter final mark : ");
                           scanf("%d",&exa12[i]);
                           fflush(stdin);
            printf("Social Responsibility And Ethics : \n");
                           printf("Please enter quiz mark : ");
                           scanf("%d",&exa13[i]);
                           fflush(stdin);
                           printf("Please enter mid-term mark : ");
                           scanf("%d",&exa14[i]);
                           fflush(stdin);
                           printf("Please enter final mark : ");
                           scanf("%d",&exa15[i]);
                           fflush(stdin);
                           
            printf("Turkish Language - I : \n");
                           printf("Please enter quiz mark : ");
                           scanf("%d",&exa16[i]);
                           fflush(stdin);
                           printf("Please enter mid-term mark : ");
                           scanf("%d",&exa17[i]);
                           fflush(stdin);
                           printf("Please enter final mark : ");
                           scanf("%d",&exa18[i]);
                           fflush(stdin);
            printf("Professinoal English - I :\n");
                           printf("Please enter 1st quiz mark : ");
                           scanf("%d",&exa19[i]);
                           fflush(stdin);
                           printf("Please enter 2nd quiz mark: ");
                           scanf("%d",&exa20[i]);
                           fflush(stdin);
                           printf("Please enter mid-term mark : ");
                           scanf("%d",&exa21[i]);
                           fflush(stdin);
                           printf("Please enter final mark : ");
                           scanf("%d",&exa22[i]);
                           fflush(stdin);
                           }
         for(i=0;i<2;i++){
                           average+=0.1*exa1[i]+0.1*exa2[i]+0.4*exa3[i]+0.4*exa4[i];
                           average1+=0.1*exa5[i]+0.1*exa6[i]+0.4*exa7[i]+0.4*exa8[i];
                           average2+=0.1*exa9[i]+0.1*exa10[i]+0.4*exa11[i]+0.4*exa12[i];
                           average3+=0.1*exa13[i]+0.4*exa14[i]+0.4*exa15[i];
                           average4+=0.1*exa16[i]+0.4*exa17[i]+0.4*exa18[i];
                           average5+=0.1*exa19[i]+0.1*exa20[i]+0.4*exa21[i]+0.4*exa22[i];
                           
                           }
         average=average/2.0;
         average1=average1/2.0;
         average2=average2/2.0;
         average3=average3/2.0;
         average4=average4/2.0;
         average5=average5/2.0;
         for(i=0;i<2;i++){
                           printf("\n");
                           printf("Name : %s\n",name[i]);
                           printf("Surname : %s\n",surname[i]);
                           printf("Calculus :\n\n");
                           printf("1.Quiz : %d\n",exa1[i]);
                           printf("2.Quiz : %d\n",exa2[i]);
                           printf("Mid-Term : %d\n",exa3[i]);
                           printf("Final: %d\n",exa4[i]);
                           printf("Average : %.2lf\n",(0.1*exa1[i]+0.1*exa2[i]+0.4*exa3[i]+0.4*exa4[i]));
                           printf("Class Average : %.2f\n\n",average);
                           printf("Computer Programming - I :\n\n");
                           printf("1.Quiz : %d\n",exa5[i]);
                           printf("2.Quiz : %d\n",exa6[i]);
                           printf("Mid-Term : %d\n",exa7[i]);
                           printf("Final: %d\n",exa8[i]);
                           printf("Average : %.2lf\n",(0.1*exa5[i]+0.1*exa6[i]+0.4*exa7[i]+0.4*exa8[i]));
                           printf("Class Average : %.2f\n\n",average1);
                           printf("Physics - I :\n\n");
                           printf("1.Quiz : %d\n",exa9[i]);
                           printf("2.Quiz : %d\n",exa10[i]);
                           printf("Mid-Term : %d\n",exa11[i]);
                           printf("Final: %d\n",exa12[i]);
                           printf("Average : %.2lf\n",(0.1*exa9[i]+0.1*exa10[i]+0.4*exa11[i]+0.4*exa12[i]));
                           printf("Class Average : %.2f\n\n",average2);
                           printf("Social Responsibility And Ethics :\n\n");
                           printf("1.Quiz : %d\n",exa13[i]);
                           printf("Mid-Term : %d\n",exa14[i]);
                           printf("Final: %d\n",exa15[i]);
                           printf("Average : %.2lf\n",(0.1*exa13[i]+0.1*exa14[i]+0.4*exa15[i]));
                           printf("Class Average : %.2f\n\n",average3);
                           printf("Turkish Language - II :\n\n");
                           printf("1.Quiz : %d\n",exa16[i]);
                           printf("Mid-Term : %d\n",exa17[i]);
                           printf("Final: %d\n",exa18[i]);
                           printf("Average : %.2lf\n",(0.1*exa16[i]+0.1*exa17[i]+0.4*exa18[i]));
                           printf("Class Average : %.2f\n\n",average4);
                           printf("Physics - I :\n\n");
                           printf("1.Quiz : %d\n",exa19[i]);
                           printf("2.Quiz : %d\n",exa20[i]);
                           printf("Mid-Term : %d\n",exa21[i]);
                           printf("Final: %d\n",exa22[i]);
                           printf("Average : %.2lf\n",(0.1*exa19[i]+0.1*exa20[i]+0.4*exa21[i]+0.4*exa22[i]));
                           printf("Class Average : %.2f\n\n",average5);
                           }
                           printf("Do you want to continue (Y / N) : ");
                           scanf("%c",&c);
                           fflush(stdin);
         }while(c!='N');
         return 0;
         getch();
}
